In [ ]:
#good to know
#import sys
#print('Python version ' + sys.version)
#print('Pandas version: ' + pd.__version__)

In [1]:
#import basic py library
# import numpy as np
# import pandas as pd

# then import the plotting fx

#from scipy import stats,integrate
#import matplotlib.pyplot as plt

#NEED plt parameters foor graphic output!!

In [2]:
# name and read the excel file
# xx=pd.read_excel('C:/Users/mjc341/desktop/folder_location/name_of_file.xlsx')

In [3]:
# enter name of file for example xx and will display the entire dateframe but fit to screen

In [4]:
#now import seaborn for viz
# import seaborn as sns
# sns.set (color_codes=True)

In [6]:
#read csv the same way
#import csv
# xx2=pd.read_csv("http://pythonhow.com/wp-content/uploads/2016/01/Income_data.csv") This is a sample file online
# enter xx2 to see the dataframe
#Have to save as csv DOS file not excel csv or PY cant read it, Save downloaded csv files as csv DOS
# to set an index as a key value
# make the applicant ID the key value
#xxindexed=xx.set_index('name-of-col') for example if empl ID will be the index or key value
# make the applicant ID the key value
#dfindexed=df2.set_index('APPLICANT_ID')

In [ ]:
#CLEAN YOUR DATA CREATE a na values list and place it before the read statement ALSO Change numbers that are NIT numbers to strings
#na_values = ['NO CLUE', 'N/A', '0']
#requests = pd.read_csv('YOUR.csv', na_values=na_values, dtype={'COL of numbers that are not INTEGERS': str}) THIS did not work w excel
# then look at your list  
# I USED dis[['STUDENT_ID']]= dis[['STUDENT_ID']].astype(str) and it WORKED
#df['NON_INT].unique()
#FIND ROWs with DASHES or some other incorrect value
#rows_with_dashes = requests['NON_INT'].str.contains('-').fillna(False) giving you any thing in that col that has a dash
#len(requests[rows_with_dashes]) 
#5 in this case 5 rows
#then look at the rows 
#requests[rows_with_dashes] you will see the cell that have dashes in them
# YOU COULD delete them by using requests['Incident Zip'][rows_with_dashes] = np.nan
#or investigate long_zip_codes = requests['Incident Zip'].str.len() > 5
#requests['Incident Zip'][long_zip_codes].unique()
#array(['77092-2016', '55164-0737', '000000', '11549-3650', '29616-0759',
#'35209-3114'], dtype=object) 
#these can be truncated by using str.slice  ....requests['Incident Zip'] = requests['Incident Zip'].str.slice(0, 5)
# LOOK at a specific problem in the rows ---> requests[requests['Incident Zip'] == '00000']
#SO SET THEM to nanzero_zips = requests['Incident Zip'] == '00000'
#requests['Incident Zip'][zero_zips] = np.nan now VIEW AND SORT ASCENDING
#unique_zips = requests['Incident Zip'].unique()
#unique_zips.sort()
#unique_zips
#YOU CAN SORT by a certain field USE  ---> .sort('colname')

In [ ]:
#CLEAN DATA PROCESS USING ZIP CODES as EXAMPLES
#na_values = ['NO CLUE', 'N/A', '0']
#requests = pd.read_csv('../data/311-service-requests.csv', 
                       #na_values=na_values, 
                       #dtype={'Incident Zip': str})
#def fix_zip_codes(zips):
    # Truncate everything to length 5 
    #zips = zips.str.slice(0, 5)
    
    # Set 00000 zip codes to nan
    #zero_zips = zips == '00000'
    #zips[zero_zips] = np.nan
    
    #return zips
#In [19]:
#requests['Incident Zip'] = fix_zip_codes(requests['Incident Zip'])
#In [20]:
#requests['Incident Zip'].unique()

In [7]:
#GET information about your dataframe
# type (xx) will describe the object such as [OUT] pandas.core.frame.DataFrame

# to get information about the type of each entry every column will be described use
# xx.info()
# see all the values use 
# xx.values

In [ ]:
#COUNT STRNG VALUES
#data['COL_W_NON_INT'].str.upper().value_counts()
#OR
#len(df.index)
#OR
#df.shape
#OR
#df['col_name].count()
#SO whats the difference between value_counts AND .count OK Value counts will give the individual values counted in a col
#EXAMPLE 
#df3['NOTIFICATION_PLAN'].value_counts()
#GIVES  the NAME AND QUANTITY of each value in the col
#EA     116
#REG     74
#ED1      6
#ED2      3
#Name: NOTIFICATION_PLAN, dtype: int64
# can also count 1s and 0s

#df3['ADMITTED'].value_counts()
#0    104
#1     95
#Name: ADMITTED, dtype: int64

In [9]:
# select an entire column
# xx ['Column_Name']
## select an entire row
# xx.loc [index or row_name]
## only show the first 5 rows transposed
#xx[:5].T

In [10]:
#show the top or bot 5 of the dataframe
#xx.head()
#xx.tail()
# Show the columns the cols will display as a list
# xx.columns
# Select multiple cols by name
#select  multiple cols by label
# xx.loc[:,['COL_NAME_1','COl_NAME_2']] this will give you  all rows because of  _:_

In [5]:
# will read a csv file as text no cols each line is read as text with no dataframe DOS or ExcelCSV same 
#import pandas as pd
#import csv
#reader = csv.reader(open ('C:/Users/mjc341/desktop/TESTPY/PYtest1.csv',newline=''),delimiter=',',quotechar='|')
#for row in reader:
        #print (','.join(row))
    #Have to save as csv DOS file not excel csv or PY cant read it so EXCEL csv has to be saved as csv DOS
# to find the type enter  type (df) your answer will be ... pandas.core.frame.DataFrame
# to select a row # select an entire row
#df.loc ['row_name']
# only show the first 5 rows transposed
#df2[:5].T
# get information about the type of each entry
#df2.info()
# get info about the index 
#df2.index
#RangeIndex(start=0, stop=99, step=1)
#select  multiple cols by label
#df2.loc[0:4,['APPLICANT_ID','APPLICANT_NAME']]
#explicitly slice rows
#df2.iloc[1:3,:]

In [11]:
# ONE way to determine if there are duplicate values in a col USE for KEY INDEX dups
#if xx['COL_NAME_'].size == dfx['COL_NAME'].unique().size:
    #print("Unique")
#else:
    #print("Not unique")
    
# YOU can also create a col that track the dups
 #dfx['dupes'] = dfx.duplicated('APPLICANT_ID',) [dupes] is the new col in the df will have boolean True or False
    

In [12]:
#COUNT Values
#xx['COLUMN_NAME'].count()  ALSO min, max,sum, median
#Get descriptive statistics for a specified column

#Statistics I have tested this works great
#dfx.col_name.describe()  for integers values gives mean std min max quartiles

#Group data and obtain the mean values   grpagg = ver.groupby('COLUMN_NAME').aggregate(np.mean)
#grpagg

#Group data and get the sums
#grpsum = ver.groupby('COLUMN_name').aggregate(np.sum)
#grpsum

In [13]:
#MELT Operation
# pd.melt(dfx, id_vars=['APPLICANT_ID'], value_vars=['APPLICANT_ETHNIC_GROUP']).head(5) this will melt one col into another by sorting the 
#1st col values by the 2nd col values this will give us each applicant ID by ethnic group the ID var by the value Var

#ANother way to sort is by creating a crosstab
#pd.crosstab(dfx['APPLICANT_ID'],dfx['APPLICANT_ETHNIC_GROUP']).head(10) Ethnic group will be the header and Applicant ID will be the rows

In [14]:
#make a subset of a certain value
# dfxsubset = dfx[(dfx['NET_DEPOSITS']== 1)] this will give all the rows where NET DEP  == 1

In [ ]:
#demog1= dfx.groupby(['APPLICANT_ETHNIC_GROUP','GENDER']).sum()  Remove Applicant ID col and use sum of Applicant count col

In [ ]:
####OMG CHANGE THE INDEX VALUE df1= df.set_index('col_name')

In [1]:
# get 1 column 
#dis['ACAD_GROUP'] #first 5 rows all columns
#dis[:5]
#combine 8 and 10 IN THE SAME LINE to get 1st 5 rows of  certain col
#dis['ACAD_GROUP'][:5]
#Select a subset of cols and first 10 rows
#dis [['ACAD_GROUP','IGRANT']][:10]

In [2]:
#Get a count of values by col name
#dis['ACAD_GROUP'].value_counts()

In [3]:
#PLT style
# plt.style.use('classic')

In [4]:
# Get a value in a col = to the desired value To get the noise complaints, 
#we need to find the rows where the "Complaint Type" column is "Noise - Street/Sidewalk". 
#noise_complaints = complaints[complaints['Complaint Type'] == "Noise - Street/Sidewalk"]
#noise_complaints[:3]

#You can also combine more than one condition with the & operator like this:
#is_noise = complaints['Complaint Type'] == "Noise - Street/Sidewalk"
#in_brooklyn = complaints['Borough'] == "BROOKLYN"
#complaints[is_noise & in_brooklyn][:5]

In [6]:
# dir()

In [8]:
#inp = input('Enter Fahrenheit Temperature:')
#try:
#fahr = float(inp)
#cel = (fahr - 32.0) * 5.0 / 9.0
#print (cel)
#except:
#print ('Thats not a number')
    
#Enter Fahrenheit Temperature:forty
#Thats not a number

In [11]:
#for i in range (10):
#x = random.random()
#print (x)

#for i in range (10):
#x = random.randint(5,100)

#print (x)

In [12]:
#GROUPING 
#Get descriptive statistics for a specified column
#dfx.col_name.describe()  for integers values gives mean std min max quartiles
#Group data and obtain the mean values   grpagg = ver.groupby('purchaser_type_name').aggregate(np.mean)
#grpagg
#Group data and get the sums
#grpsum = ver.groupby('purchaser_type_name').aggregate(np.sum)
#grpsum

In [ ]:
#MUNGE
#CREATE CATEGORICAL ranges
#incomeranges =pd.cut(df['value_col'], 14) the #14 is the number of ranges you want

#GET the UNIQUE values of a col by name gives you an array
#df['COL_NAME'].unique()

#GET a binary indicator
#df.ix[:,'COL A'] == "VALUE you are checking"

#obtain the data types in the cols
#df.dtypes

In [1]:

#combine conditions in a dataset 
#df2 = df['name_of_Col 1'] == "aValueInCol 1"
#df3 = df['name of Col 2'] == "Avaluein Col 2"  you will get the entire row all of the other values in that row are included
#df[is_noise & in_brooklyn][:5] return the 1st 5 rows of df2 anf df 3 combined and replace the original df with that df if you 
#wanted to keep the original df then youd name the new combined df as df4 or something if you only want a few of the columns from 
#those row then use:complaints[is_noise & in_brooklyn][['Complaint Type', 'Borough', 'Created Date', 'Descriptor']][:10]


In [5]:
# A column in Pandas is a SERIES 
import pandas as pd
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [6]:
import numpy as np

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
pd.Series([1,2,3]).values

array([1, 2, 3], dtype=int64)

In [9]:
#pandas Series are internally numpy arrays. If you add .values to the end of any Series, you'll get its internal numpy array
# that is why you can get boolian selection reponses out of columns because NP arrys have bool quality
arr=np.array([1,2,3])

In [10]:
arr!=2

array([ True, False,  True], dtype=bool)

In [11]:
arr[arr!=2]

array([1, 3])

In [12]:
#Check if Py 3 is using integer division which means every divded int will be rounded off to the nearest whole number
#ifso then you have to change your values to floats and then you can get decimal results to divide then
#noise_complaint_counts = noise_complaints['Borough'].value_counts()
#complaint_counts = complaints['Borough'].value_counts()
#noise_complaint_counts / complaint_counts.astype(float)
#[in]#noise_complaint_counts / complaint_counts

In [13]:
#DATAFRAME .groupby() is like SQL
#In this case, berri_bikes.groupby('weekday').aggregate(sum) 
#weekday_counts = berri_bikes.groupby('weekday').aggregate(sum)
#weekday_counts this will display the results
#means "Group the rows by weekday and then add up all the values with the same weekday".
# so group the rows by 'ethnicity' and ad up all the values with the same ethnicicty/school/GPA etc
# you can rename the index in this example the weekdays are number values to replace that witht he name of the day use 
#weekday_counts.index = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
# THEN plot it weekday_counts.plot(kind='bar')



In [ ]:
#TO combine files into a dataframe STACKED  if all cols are the same then use dfnamne = pd.concat(name of file(s))